import Head from "next/head";
import Navbar from "../components/Navbar";
import Loader from "../components/Loader";
import gsap from "gsap";
import { useEffect } from "react";
import { HeroSection } from "../components/HeroSection";
import { Sound } from "../components";
import LaunchTeaser from "../components/LaunchTeaser";

export default function Home() {
  useEffect(() => {
    const tl = gsap.timeline();

    tl.to(".Nav", {
      autoAlpha: 1, // Show the Nav div
      delay: 6.5, // Set the duration of the animation
    });
  }, []);
  return (
    <div className="bg-[#000]">
      <Head>
        <title>DZNS Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LaunchTeaser />

        {/* <div className="overflow-hidden fixed h-full w-full">
          <Loader />
        </div>

        <div className="Nav h-full w-full invisible">
          <HeroSection />
        </div> */}
      </main>
      <div className="relative z-[5]">
        <Sound />
      </div>
    </div>
  );
}
